# Add platforms here if/when set up. See the GitHub docs for valid keys:
# https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository
#
# Examples (uncomment + fill when you have accounts):
# github: [twarc-net]
# ko_fi: twarc
# custom: ["https://twarc.net/donate"]
